project:
  type: book  
  output-dir: docs

book:
  title: "Evaluation of Probability that a Bridge Collpases in Omaha, NE "
  author: "Tyler Davis"
  page-footer:
    left: "Copyright 2025, Tyler Davis"
  chapters:
    - introduction.qmd
    - Methods.qmd
    - draft-results.qmd
    - conclusion.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - draft-data-doc.qmd
    - Analysis.qmd
    - index.qmd

bibliography: references.bib

execute:
    error: true

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



