---
title: "Conclusion"
editor: visual
---

```{r}
#| echo: false
#| message: false
#| warning: false
#| results: hide
options(digits = 4)
library(tidyverse)
library(dplyr)
library(psych)
library(knitr)
library(psych)

omaha_bridges <- read.csv("omaha_bridges.csv")

fil_dat <- omaha_bridges %>%
  select(c(1,2,5,15,21,22,25, 28:29,31:32, 68:77,88,103,107,112,116, 122:125))
col <- data.frame(colnames(fil_dat))

fil_dat <- fil_dat %>%
  mutate(across(everything(), ~ ifelse(. == "N", NA, .)))

bridge_cond1 <- fil_dat %>%
 filter(
   BRIDGE_CONDITION == "P"
 ) %>%
   select(c(8,9,10,12:16,21,26,27))

high_traffic <- bridge_cond1 %>%
  filter (
    ADT_029 > 5000 & TRAFFIC_LANES_ON_028A > 2
  )

desc_brid_cond <- describe(bridge_cond1)
desc_h_t <- describe(high_traffic)

desc_brid_cond %>%
  select(mean, sd, n, median) %>%
  mutate(across(c(mean, sd, median), ~ format(round(.x, 3), scientific = FALSE))) %>%
  kable()

desc_h_t %>%
  select(mean, sd, n, median) %>%
  mutate(across(c(mean, sd, median),~ format(round(.x, 3), scientific = FALSE)))%>%
  kable()


options(digits = 4)
percents <- data.frame(
  "bridges at risk" = nrow(bridge_cond1)/nrow(fil_dat),
  "High traffic bridges at risk" = nrow(high_traffic)/nrow(fil_dat))
kable(percents, col.names = c("Bridges at Risk", "High Traffic Bridges at Risk"))

Omaha <- fil_dat %>%
  mutate(collapse_risk = ifelse(BRIDGE_CONDITION == "P" & STRUCTURAL_EVAL_067 <= 4, 1, 0)) %>%
  select(c(1,8,12,18,26,31))

library(VIM)
one <- kNN(Omaha, k = 5)


library(caret)
train_indices <- createDataPartition(one$OBJECTID, 
                                     p = 0.8, 
                                     list = FALSE)

train_data <- one[train_indices, ]

# Testing data
test_data <- one[-train_indices, ]


# Logistic regression model
model1 <- glm(collapse_risk ~as.numeric(DECK_COND_058) + OPERATING_RATING_064 + as.numeric(YEAR_BUILT_027), 
             family = binomial(link = "logit"), data = train_data)

library(gt)
library(broom)

tidy(model1) %>%
  gt()

predicted_probabilities <- predict(model1, newdata = test_data, type = "response")

predicted_classes <- ifelse(predicted_probabilities > 0.5, 1, 0)

prop_pred <- mean(predicted_classes)
omaha_c <- mean(Omaha$collapse_risk)

actual_classes <- test_data$collapse_risk
 # Compare predicted vs actual values
comparison <- data.frame(Actual = actual_classes, Predicted = predicted_classes)
 
accuracy <- mean(predicted_classes == actual_classes)
kable(accuracy,col.names = c("Accuracy"))

```

When looking back at the opening question, do you ever think of how stable a bridge is when you are driving over top of it, the answer would be hopefully not. This is because in the analysis we have found that `r signif(100*percents$bridges.at.risk,3)`% of the bridges in the Omaha,NE area have a bridge rating of "poor". We have also see that `r signif(100*percents$High.traffic.bridges.at.risk,3)`% of bridges are considered high traffic bridges and also have a "poor" rating. This shows that in Omaha, NE if you took a random sample of 100 bridges, 5 would come out with a "poor" rating. This is a major issue highlighting the lack of infrastructure maintenance and repair in the country. This is a future concern and with bridges and roads only getting older it is time to put more money and research into how to maintain the aging infrastructure.

This prompted further investigation using the National Bridge Inventory data set which lead to the creation of a collapse variable based on summary variables and the formation of a generalized linear model. This was done to try and estimate the proportion of bridges that are at risk of collapse. The model estimated that `r signif(100*prop_pred,3)` % of bridges in Omaha are at risk of collapse. This is similar to what was found in the descriptive statistics and was predicted with a `r signif(100*accuracy,3)`% accuracy.

Some issues that occur in the analysis is that there is no specifically defined criteria for if a bridge is going to collapse. This creates a issue when trying to predict or categorize if a bridge will collapse. This lead to the analyzing the descriptive statistics while also formulating a variable that categorized risk of collapse. This collapse variable was formed from two variables that were summary variables in themselves of bridge condition and structure. This lead to a variable that in many ways categorized the risk of collapse. The data set itself contains a lot of missing values, which is difficult to deal with hence when the model was created an imputed data set was used so that those missing values were then estimated.

Future implications of this research is using this model to further categorize bridges as at risk or needing attention. This will allow researchers to quickly evaluate if a bridge is in need of attention. This could allow government official to act quicker if they know the proportion of bridges that are at risk in there district or state. This will also lead to more economical solution as if at risk bridges can be identified then there will not be a need to fix collapsed bridges if action is taken. Overall, the main product of this analysis is that bridges are not in good condition and money need to be allocated to help mend and fix bridges so that we do not have another collapse in a major city like the Francis Scott Key Bridge in Baltimore, MD.
