---
title: "Introduction"
editor: visual
---

Have you ever been driving over a bridge and wondering how stable it is? This is a question that has created a lot of buzz recently especially with the state of the infrastructure in the United States. Recently the United States received a C rating on their infrastructure, which is the highest they have ever received, @gomesAmericasInfrastructureEarns2025 . This tells us that the overall infrastructure is slightly improving over time, yet it is still at a C. What does this tell us about the future of infrastructure in this county will it continue to improve or is this just a flash in the pan? This is an important question to ask as many people depend on the bridges and roads in this country to get to their job or to see loved ones and at this point they are not dependable. The most recent example being the Francis Scott Key Bridge in Baltimore, MD, which collapsed after a cargo ship hit it, @deletterBaltimoresKeyBridge2024 . This collapse lead to great economic disruption in the area and also shined a light again on the state of infrastructure in the country. This is the not the first major bridge of its kind to collapse, as the I - 35 W Mississippi River Bridge located in Minneapolis, MN collapsed in 2007. This bridge collapse killed and injured many people, while also causing massive economic disruption as it was the third busiest bridge in Minneapolis, @deletterBaltimoresKeyBridge2024 .

This past year the National Transportation Safety Board has flagged 68 bridges across the United States that are at risk of collapse from vessel strikes, @NTSBRecommends682025 . The NTSB also found that, " the Key Bridge, which collapsed after being struck by the container ship Dali on March 26, 2024, was almost 30 times above the acceptable risk threshold for critical or essential bridges..." @NTSBRecommends682025.

These issues throughout the U.S. bring up questions regarding the state of bridges close to home. When looking at the bridge condition in Nebraska, this leads to the discovery that 8.8% of bridges are structurally deficient. It can also be found that 149 dams are considered high hazard potential, and Nebraskans are already paying billions without the issue being solved, @NebraskaInfrastructureReport2025 . This shows that changes need to be made, but what about the condition of bridges in the states biggest city?

The question that will be dissected in this report is the probability of a bridge collapse in Omaha, NE. This problem will be answered by analyzing the NDAT National Bridge Inventory data set, which contains a variety of information regarding each bridge in the U.S., more information about the data set can be found in the data documentation. The data set will then be filtered to focus in on the Omaha area including surrounding areas such as Elkhorn, NE and Council Bluffs, IA. The bridge quality and structural integrity will then be analyzed using condition based variables. A linear model will then be constructed using a curated response variable to predict the next bridge collapse. In the end, we aim to understand the probability that a bridge in Omaha is at risk of collapse and have the ability to predict it.
